### GET ALL SONGS
GET https://music-eqw2.onrender.com/songs/

### GET ONE SONG
GET http://localhost:8080/songs/64690d4135aaf654dd5ee73d 

### GET ONE SONG
GET https://music-eqw2.onrender.com/songs/64690d4135aaf654dd5ee73d
### CREATE SONG
POST http://localhost:8080/songs/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Day",
    "email": "fake@gmail.com",
    "favoriteColor": "Green",
    "birthday": "07/21/2000"
}

### DELETE SONG
DELETE http://localhost:8080/songs/6456dbe2d5e3521294d62bb6 HTTP/1.1

### PUT SONG
PUT http://localhost:8080/songs/6456dc0bd5e3521294d62bb7 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jason",
    "lastName": "Day",
    "email": "fakemail@outlook.com",
    "favoriteColor": "Blue",
    "birthday": "10/10/2005"
}
