### GET ALL SONGS RENDER
GET https://musicclass.onrender.com/songs/

### GET ONE SONG RENDER
GET https://musicclass.onrender.com/songs/6469308568841fd397917ddc

### CREATE SONG RENDER
POST https://musicclass.onrender.com/songs/ HTTP/1.1
Content-Type: application/json

{
    "name": "Go the Distance 2",
    "featuredIn": "Hercules",
    "composer": "Alan Menkin",
    "aranger": "Jaden Day",
    "lyricist": "David Zippel",
    "year": "1997",
    "key": "D"
  }

### DELETE SONG RENDER
DELETE https://musicclass.onrender.com/songs/64692da2c827416329e48ba8 HTTP/1.1

### PUT SONG RENDER
PUT https://musicclass.onrender.com/songs/646909dd35aaf654dd5ee739 HTTP/1.1
Content-Type: application/json

{
    "name": "Go the Distance",
    "featuredIn": "Hercules",
    "composer": "Alan Menkin",
    "aranger": "Jaden Kent Day",
    "lyricist": "David Zippel",
    "year": "1997",
    "key": "D"
}
### GET ALL STUDENTS RENDER
GET https://musicclass.onrender.com/students/

### GET ONE STUDENT RENDER
GET https://musicclass.onrender.com/students/64690d4135aaf654dd5ee73e

### CREATE STUDENT RENDER
POST https://musicclass.onrender.com/students/ HTTP/1.1
Content-Type: application/json

{
    "name": "Jaden",
    "instruments": "Piano, Violin, Cello" 
  }

### PUT STUDENT RENDER
PUT https://musicclass.onrender.com/students/64692ec1c827416329e48bab HTTP/1.1
Content-Type: application/json

{
   "name": "Jaden",
    "instruments": "Piano, Violin, Cello, Organ" 
}

### DELETE STUDENT RENDER
DELETE https://musicclass.onrender.com/students/64692e8dc827416329e48baa HTTP/1.1


### GET ALL SONGS LOCALHOST
GET http://localhost:8080/songs/

### GET ONE SONG LOCALHOST
GET http://localhost:8080/songs/64690d4135aaf654dd5ee73d 

### CREATE SONG LOCALHOST
POST http://localhost:8080/songs/ HTTP/1.1
Content-Type: application/json

{
    "name": "Go the Distance 2",
    "featuredIn": "Hercules",
    "composer": "Alan Menkin",
    "aranger": "Jaden Day",
    "lyricist": "David Zippel",
    "year": "1997",
    "key": "D"
  }

### DELETE SONG LOCALHOST
DELETE http://localhost:8080/songs/6456dbe2d5e3521294d62bb6 HTTP/1.1

### PUT SONG LOCALHOST
PUT http://localhost:8080/songs/6456dc0bd5e3521294d62bb7 HTTP/1.1
Content-Type: application/json

{
    "name": "Go the Distance",
    "featuredIn": "Hercules",
    "composer": "Alan Menkin",
    "aranger": "Jaden Day",
    "lyricist": "David Zippel",
    "year": "1997",
    "key": "D"
}

### GET ALL STUDENTS RENDER
GET http://localhost:8080/students/

### GET ONE STUDENT RENDER
GET http://localhost:8080/students/64690d4135aaf654dd5ee73d

### CREATE STUDENT RENDER
POST http://localhost:8080/students/ HTTP/1.1
Content-Type: application/json

{
    "name": "Jaden",
    "instruments": "Piano, Violin, Cello" 
  }

### PUT STUDENT RENDER
PUT http://localhost:8080/students/64692f3a6be0102407f47247 HTTP/1.1
Content-Type: application/json

{
   "name": "Jaden",
    "instruments": "Piano, Violin, Cello, Organ" 
}

### DELETE STUDENT RENDER
DELETE http://localhost:8080/students/64692ec1c827416329e48bab HTTP/1.1
